# Generated by Django 3.1.4 on 2020-12-27 15:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0003_auto_20201227_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='focus',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
