# Generated by Django 3.1.4 on 2021-01-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0004_auto_20201227_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='img/post/personal.png', upload_to='post'),
        ),
    ]
